#!/usr/bin/perl

use warnings; 
use strict; 
use POSIX qw(ceil);

my $count = shift or die "Please call $0 count startdeep";
my $deep = shift or die "Please call $0 count startdeep";

my $factor = $deep;
my @alphabet = split('', 'abcdefghijklmnopqrstuvwxyz');

my $date = localtime();
my $gcode = qq|(Gcode generated by $0 for Eagle PCB Widget $date)
G21 (mm mode)
G90 (abs mode)
M3 (spindle on)
TO M6 (set tool)
G0 Z1
(------ DISPENSER DROP\'s -------)
M5 (spindle stop)
|;

for(my$i=0;$i<=$count;$i++){
   my $y = $i * 2;
   for(my$j=0;$j<=$count;$j++){
      my $x = $j * 2;
      $gcode .= set_drop($i, $j, $x, $y, $deep);
   }
   $deep += $factor;
}

$gcode .= qq|
M5 (spindle stop)
M30 (prog stop)
|;

print $gcode;

exit;

sub set_drop {
   my($i, $j, $x, $y, $deep) = @_;
   my $letter = $alphabet[$j];
   return "(generate Drop $i$letter press: $deep)
G0 Z1
G0 X$x y$y
G0 Z0.5
G1 Z0.3333
(chilipeppr_pause drop$i$letter G1 F100 X$deep)
G1 Z0.5
";
}